config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#index"
  get :dashboard, to: 'dashboard#index'

  get 'sessions/new'
  get    '/signup',   to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  namespace :teacher do
    resources :courses
    get 'quizzes/:id/questions', to: 'quizzes#questions_by_quiz_id'
    resources :quizzes
    resources :questions
  end
  namespace :teacher do
    
  end
  resources :users
end

app/controllers/student/quizzes_controller.rb
class Student::QuizzesController < ApplicationController
end

app/controllers/teacher/courses_controller.rb
class Teacher::CoursesController < ApplicationController
    before_filter :check_role
    def index
        @courses = Course.where(user_id: current_user.id)
    end
    def new 
        @course = Course.new
    end

    def create
        @course = Course.new(course_params)
        @course.user_id = current_user.id
        if @course.save
            log_in @course
            flash[:success] = "The Course has been created"
            redirect_to teacher_courses_path
        else
            render 'new'
        end
    end
    
    def edit
        @course = Course.find(params[:id])
    end

    def update
        @course = Course.find(params[:id])
        if @course.update(course_params)
            flash[:success] = "Course has ben saved"
            redirect_to edit_teacher_course_path(@course)
        else
            render 'edit'
        end 
    end

    def destroy
        @course = Course.find(params[:id])
        @course.destroy
        flash[:success] = "Course has ben deleted"
        redirect_to courses_redirect_path
    end

    private 
        def course_params
            params.require(:course).permit(:title)
        end
        
        def check_role
            if !is_teacher?
                redirect_to '/login'
            end
        end
end

app/controllers/teacher/questions_controller.rb
class Teacher::QuestionsController < ApplicationController
    def create
        @question = Question.new(question_params)
        if @question.save
            log_in @question
            flash[:success] = "The Question has been created"
            redirect_to "/teacher/quizzes/#{@question.quiz_id}/questions"
        else
            render 'new'
        end
    end

    def edit
        @question = Question.find(params[:id])
    end

    def update
        @question = Question.find(params[:id])
        if @question.update(question_params)
            flash[:success] = "Question has ben saved"
            redirect_to edit_teacher_quiz_path(@question)
        else
            render 'edit'
        end
    end

    def destroy
        @question = Question.find(params[:id])
        @question.destroy
        flash[:success] = "Question has ben deleted"
        redirect_to "/teacher/quizzes/#{@question.quiz_id}/questions"
    end

    private 
        def question_params
            params.require(:question).permit(:description, :answer_digest, :quiz_id)
        end
        
        def check_role
            if !is_teacher?
                redirect_to '/login'
            end
        end

end

app/controllers/teacher/quizzes_controller.rb
class Teacher::QuizzesController < ApplicationController
    def index
        @quizzes = Quiz.joins(:course).where(:courses => { :user_id => current_user.id} )
    end

    def questions_by_quiz_id
        @quiz = Quiz.find(params[:id])
        @questions = Question.where(:quiz_id => params[:id])
    end

    def new 
        @quiz = Quiz.new
    end

    def create
        @quiz = Quiz.new(quiz_params)
        if @quiz.save
            log_in @quiz
            flash[:success] = "The Quiz has been created"
            redirect_to teacher_quizzes_path
        else
            render 'new'
        end
    end
    
    def edit
        @quiz = Quiz.find(params[:id])
    end

    def update
        @quiz = Quiz.find(params[:id])
        if @quiz.update(quiz_params)
            flash[:success] = "Quiz has ben saved"
            redirect_to edit_teacher_quiz_path(@quiz)
        else
            render 'edit'
        end 
    end

    def destroy
        @quiz = Quiz.find(params[:id])
        @quiz.destroy
        flash[:success] = "Quiz has ben deleted"
        redirect_to quizzes_redirect_path
    end

    private 
        def quiz_params
            params.require(:quiz).permit(:title, :course_id)
        end
        
        def check_role
            if !is_teacher?
                redirect_to '/login'
            end
        end
end

app/helpers/student/quizzes_helper.rb
module Student::QuizzesHelper
end

app/helpers/teacher/courses_helper.rb
module Teacher::CoursesHelper
end

app/helpers/teacher/questions_helper.rb
module Teacher::QuestionsHelper
    def questions_total(id)
        Question.where(quiz_id: id).count
    end
end

app/helpers/teacher/quizzes_helper.rb
module Teacher::QuizzesHelper
end

app/views/teacher/quizzes/edit.html.erb
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
        <div class="title_left">
            <h3>Course</h3>
        </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
            <div class="x_title">
                <h2>Course<small>Edit</small></h2>
                
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <form id="demo-form2" action="/teacher/courses/<%= @course.id %>" method="post" data-parsley-validate class="form-horizontal form-label-left">
                <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                <input type="hidden" name="_method" value="put" />
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">Course Title <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" id="title" name="course[title]" value="<%= @course.title %>" required="required" class="form-control col-md-7 col-xs-12">
                    </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Cancel</button>
                    <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>

                </form>
            </div>
            </div>
        </div>
        </div>

    </div>
</div>
      <!-- /page content -->

app/views/teacher/quizzes/index.html.erb
<div class="right_col" role="main">
        <div class="">

          <div class="page-title">
            <div class="title_left">
              <h3>Quiz</h3>
            </div>
          </div>
          <div class="clearfix"></div>
          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>All Quiz</h2>
                  
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <table class="table">
                      <thead>
                        <tr>
                          <th>Title</th>
                          <th>Course</th>
                          <th>Question</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                      <% @quizzes.each do |quiz|%>
                        <tr>
                          <td><%= quiz.title %></td>
                          <td><%= quiz.course.title %></td>
                          <td><%= link_to questions_total(quiz.id), "/teacher/quizzes/#{quiz.id}/questions" %></td>
                          <td><%= link_to 'Edit', edit_teacher_quiz_path(quiz) %>|<%= link_to 'Delete',  { action: :destroy, id: quiz.id }, method: :delete, data: { confirm: 'Are you sure?' } %></td>   
                        </tr>
                      <% end %>
                      </tbody>
                    </table>

                  </div>
                </div>
              </div>
            </div>
          </div>

    </div>
</div>
      <!-- /page content -->

app/views/teacher/quizzes/new.html.erb
<div class="right_col" role="main">
        <div class="">

          <div class="page-title">
            <div class="title_left">
              <h3>Quiz</h3>
            </div>
          </div>
          <div class="clearfix"></div>
          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>New Quiz<small>Create</small></h2>
                  
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                  <form id="demo-form2" action="/teacher/quizzes" method="post" data-parsley-validate class="form-horizontal form-label-left">
                    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                    <div class="form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">Quiz Title <span class="required">*</span>
                      </label>
                      <div class="col-md-6 col-sm-6 col-xs-12">
                        <input type="text" id="title" name="quiz[title]" required="required" class="form-control col-md-7 col-xs-12">
                      </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Select Course</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <select class="form-control" name="quiz[course_id]">
                            <option>Choose option</option>
                            <% Course.where(user_id: current_user.id).each do |course| %>
                              <option value="<%= course.id %>"><%= course.title %></option>
                            <% end %>
                          </select>
                        </div>
                      </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                      <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                        <button type="submit" class="btn btn-primary">Cancel</button>
                        <button type="submit" class="btn btn-success">Submit</button>
                      </div>
                    </div>

                  </form>
                </div>
              </div>
            </div>
          </div>
    </div>
</div>
      <!-- /page content -->

app/views/teacher/quizzes/questions_by_quiz_id.html.erb
<div class="right_col" role="main">
        <div class="">

          <div class="page-title">
            <div class="title_left">
              <h3>Quiz</h3>
            </div>
          </div>
          <div class="clearfix"></div>
          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><%= @quiz.title %></h2>
                  
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <table class="table">
                      <thead>
                        <tr>
                          <th>Question</th>
                          <th>Answer</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                      <% @questions.each do |question|%>
                        <tr>
                          <td><%= question.description %></td>
                          <td><%= question.answer_digest %></td>
                          <td><%= link_to 'Edit', edit_teacher_question_path(question) %>|<%= link_to 'Delete',  { action: :destroy, id: question.id }, method: :delete, data: { confirm: 'Are you sure?' } %></td>   
                        </tr>
                      <% end %>
                      </tbody>
                    </table>
                  <div class="x_title">
                  <h2>New Quiz<small>Create</small></h2>
                  
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <br />
                  <form for="questions" action="/teacher/questions" method="post" data-parsley-validate class="form-horizontal form-label-left">
                    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                    <input type="hidden" name="question[quiz_id]" value="<%= @quiz.id %>">
                    <div class="form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">Question Title <span class="required">*</span>
                      </label>
                      <div class="col-md-6 col-sm-6 col-xs-12">
                        <input type="text" id="description" name="question[description]" required="required" class="form-control col-md-7 col-xs-12">
                      </div>
                    </div>
                    <div class="form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">Answer Digest <span class="required">*</span>
                      </label>
                      <div class="col-md-6 col-sm-6 col-xs-12">
                        <input type="text" id="answer_digest" name="question[answer_digest]" required="required" class="form-control col-md-7 col-xs-12">
                      </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                      <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                        <button type="submit" class="btn btn-primary">Cancel</button>
                        <button type="submit" class="btn btn-success">Submit</button>
                      </div>
                    </div>

                  </form>
                </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

    </div>
</div>
      <!-- /page content -->